/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 101
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LTscript_GT = 1,
  anon_sym_LT_SLASHscript_GT = 2,
  sym_javascript_content = 3,
  anon_sym_LT = 4,
  anon_sym_GT = 5,
  anon_sym_LT_SLASH = 6,
  aux_sym_tag_name_token1 = 7,
  anon_sym_AT = 8,
  aux_sym_handler_attribute_token1 = 9,
  anon_sym_EQ = 10,
  aux_sym_handler_attribute_token2 = 11,
  anon_sym_POUND = 12,
  aux_sym_handler_name_token1 = 13,
  anon_sym_DQUOTE = 14,
  anon_sym_LBRACE = 15,
  anon_sym_RBRACE = 16,
  sym_text = 17,
  anon_sym_LBRACE_LBRACE = 18,
  anon_sym_RBRACE_RBRACE = 19,
  sym_expression_content = 20,
  sym_string_content = 21,
  sym_source_file = 22,
  sym_script_tag = 23,
  sym__statement = 24,
  sym_tag = 25,
  sym_content = 26,
  sym_tag_name = 27,
  sym_attributes = 28,
  sym_attribute = 29,
  sym_handler_attribute = 30,
  sym_directive_attribute = 31,
  sym_regular_attribute = 32,
  sym_handler_name = 33,
  sym_directive_name = 34,
  sym_attribute_name = 35,
  sym_quoted_string = 36,
  sym_quoted_expression = 37,
  sym_interpolation = 38,
  aux_sym_source_file_repeat1 = 39,
  aux_sym_content_repeat1 = 40,
  aux_sym_attributes_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LTscript_GT] = "<script>",
  [anon_sym_LT_SLASHscript_GT] = "</script>",
  [sym_javascript_content] = "javascript_content",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [aux_sym_tag_name_token1] = "tag_name_token1",
  [anon_sym_AT] = "@",
  [aux_sym_handler_attribute_token1] = "handler_attribute_token1",
  [anon_sym_EQ] = "=",
  [aux_sym_handler_attribute_token2] = "handler_attribute_token2",
  [anon_sym_POUND] = "#",
  [aux_sym_handler_name_token1] = "handler_name_token1",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_text] = "text",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [sym_expression_content] = "expression_content",
  [sym_string_content] = "string_content",
  [sym_source_file] = "source_file",
  [sym_script_tag] = "script_tag",
  [sym__statement] = "_statement",
  [sym_tag] = "tag",
  [sym_content] = "content",
  [sym_tag_name] = "tag_name",
  [sym_attributes] = "attributes",
  [sym_attribute] = "attribute",
  [sym_handler_attribute] = "handler_attribute",
  [sym_directive_attribute] = "directive_attribute",
  [sym_regular_attribute] = "regular_attribute",
  [sym_handler_name] = "handler_name",
  [sym_directive_name] = "directive_name",
  [sym_attribute_name] = "attribute_name",
  [sym_quoted_string] = "quoted_string",
  [sym_quoted_expression] = "quoted_expression",
  [sym_interpolation] = "interpolation",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_content_repeat1] = "content_repeat1",
  [aux_sym_attributes_repeat1] = "attributes_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LTscript_GT] = anon_sym_LTscript_GT,
  [anon_sym_LT_SLASHscript_GT] = anon_sym_LT_SLASHscript_GT,
  [sym_javascript_content] = sym_javascript_content,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [aux_sym_tag_name_token1] = aux_sym_tag_name_token1,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_handler_attribute_token1] = aux_sym_handler_attribute_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_handler_attribute_token2] = aux_sym_handler_attribute_token2,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_handler_name_token1] = aux_sym_handler_name_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_text] = sym_text,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [sym_expression_content] = sym_expression_content,
  [sym_string_content] = sym_string_content,
  [sym_source_file] = sym_source_file,
  [sym_script_tag] = sym_script_tag,
  [sym__statement] = sym__statement,
  [sym_tag] = sym_tag,
  [sym_content] = sym_content,
  [sym_tag_name] = sym_tag_name,
  [sym_attributes] = sym_attributes,
  [sym_attribute] = sym_attribute,
  [sym_handler_attribute] = sym_handler_attribute,
  [sym_directive_attribute] = sym_directive_attribute,
  [sym_regular_attribute] = sym_regular_attribute,
  [sym_handler_name] = sym_handler_name,
  [sym_directive_name] = sym_directive_name,
  [sym_attribute_name] = sym_attribute_name,
  [sym_quoted_string] = sym_quoted_string,
  [sym_quoted_expression] = sym_quoted_expression,
  [sym_interpolation] = sym_interpolation,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
  [aux_sym_attributes_repeat1] = aux_sym_attributes_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LTscript_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASHscript_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_javascript_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_tag_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_handler_attribute_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_handler_attribute_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_handler_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_expression_content] = {
    .visible = true,
    .named = true,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_script_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_handler_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_regular_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_handler_name] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_attributes_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 6,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 32,
  [42] = 42,
  [43] = 27,
  [44] = 33,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 63,
  [72] = 54,
  [73] = 73,
  [74] = 70,
  [75] = 75,
  [76] = 73,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 77,
  [91] = 88,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 87,
  [96] = 96,
  [97] = 84,
  [98] = 98,
  [99] = 80,
  [100] = 89,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '"', 40,
        '#', 38,
        '<', 29,
        '=', 36,
        '>', 30,
        '@', 34,
        '{', 41,
        '}', 43,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(38);
      if (lookahead == '<') ADVANCE(2);
      if (lookahead == '>') ADVANCE(30);
      if (lookahead == '@') ADVANCE(34);
      if (lookahead == '}') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(16);
      END_STATE();
    case 3:
      if (lookahead == '<') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 4:
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '{') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0) ADVANCE(45);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(24);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(25);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'p') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(11);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(6);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 19:
      if (lookahead == '{') ADVANCE(46);
      END_STATE();
    case 20:
      if (lookahead == '}') ADVANCE(47);
      END_STATE();
    case 21:
      if (lookahead == '}') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 22:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(49);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LTscript_GT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LT_SLASHscript_GT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_javascript_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_javascript_content);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(31);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_handler_attribute_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_handler_attribute_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_handler_name_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      if (lookahead == '}') ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '{') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(44);
      if (lookahead != 0) ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '{') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_expression_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_expression_content);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_string_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(51);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 37},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 37},
  [39] = {.lex_state = 37},
  [40] = {.lex_state = 37},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 37},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 37},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 37},
  [49] = {.lex_state = 37},
  [50] = {.lex_state = 5},
  [51] = {.lex_state = 5},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 5},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 5},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 37},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 21},
  [60] = {.lex_state = 37},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 37},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 21},
  [65] = {.lex_state = 37},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 50},
  [69] = {.lex_state = 37},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 37},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 22},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 21},
  [93] = {.lex_state = 22},
  [94] = {.lex_state = 21},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LTscript_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [aux_sym_tag_name_token1] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [aux_sym_handler_name_token1] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(83),
    [sym_script_tag] = STATE(13),
    [sym__statement] = STATE(13),
    [sym_tag] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LTscript_GT] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(9), 1,
      anon_sym_GT,
    ACTIONS(11), 1,
      aux_sym_tag_name_token1,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_POUND,
    STATE(69), 1,
      sym_attribute_name,
    STATE(80), 1,
      sym_attributes,
    STATE(4), 2,
      sym_attribute,
      aux_sym_attributes_repeat1,
    STATE(34), 3,
      sym_handler_attribute,
      sym_directive_attribute,
      sym_regular_attribute,
  [28] = 8,
    ACTIONS(11), 1,
      aux_sym_tag_name_token1,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_POUND,
    ACTIONS(17), 1,
      anon_sym_GT,
    STATE(69), 1,
      sym_attribute_name,
    STATE(99), 1,
      sym_attributes,
    STATE(4), 2,
      sym_attribute,
      aux_sym_attributes_repeat1,
    STATE(34), 3,
      sym_handler_attribute,
      sym_directive_attribute,
      sym_regular_attribute,
  [56] = 7,
    ACTIONS(11), 1,
      aux_sym_tag_name_token1,
    ACTIONS(13), 1,
      anon_sym_AT,
    ACTIONS(15), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      anon_sym_GT,
    STATE(69), 1,
      sym_attribute_name,
    STATE(5), 2,
      sym_attribute,
      aux_sym_attributes_repeat1,
    STATE(34), 3,
      sym_handler_attribute,
      sym_directive_attribute,
      sym_regular_attribute,
  [81] = 7,
    ACTIONS(21), 1,
      anon_sym_GT,
    ACTIONS(23), 1,
      aux_sym_tag_name_token1,
    ACTIONS(26), 1,
      anon_sym_AT,
    ACTIONS(29), 1,
      anon_sym_POUND,
    STATE(69), 1,
      sym_attribute_name,
    STATE(5), 2,
      sym_attribute,
      aux_sym_attributes_repeat1,
    STATE(34), 3,
      sym_handler_attribute,
      sym_directive_attribute,
      sym_regular_attribute,
  [106] = 6,
    ACTIONS(32), 1,
      anon_sym_LT,
    ACTIONS(34), 1,
      anon_sym_LT_SLASH,
    ACTIONS(36), 1,
      sym_text,
    ACTIONS(38), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(95), 1,
      sym_content,
    STATE(12), 3,
      sym_tag,
      sym_interpolation,
      aux_sym_content_repeat1,
  [127] = 6,
    ACTIONS(32), 1,
      anon_sym_LT,
    ACTIONS(36), 1,
      sym_text,
    ACTIONS(38), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(40), 1,
      anon_sym_LT_SLASH,
    STATE(84), 1,
      sym_content,
    STATE(12), 3,
      sym_tag,
      sym_interpolation,
      aux_sym_content_repeat1,
  [148] = 6,
    ACTIONS(32), 1,
      anon_sym_LT,
    ACTIONS(36), 1,
      sym_text,
    ACTIONS(38), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(42), 1,
      anon_sym_LT_SLASH,
    STATE(97), 1,
      sym_content,
    STATE(12), 3,
      sym_tag,
      sym_interpolation,
      aux_sym_content_repeat1,
  [169] = 6,
    ACTIONS(32), 1,
      anon_sym_LT,
    ACTIONS(36), 1,
      sym_text,
    ACTIONS(38), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(44), 1,
      anon_sym_LT_SLASH,
    STATE(87), 1,
      sym_content,
    STATE(12), 3,
      sym_tag,
      sym_interpolation,
      aux_sym_content_repeat1,
  [190] = 4,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    ACTIONS(48), 1,
      anon_sym_LTscript_GT,
    ACTIONS(51), 1,
      anon_sym_LT,
    STATE(10), 4,
      sym_script_tag,
      sym__statement,
      sym_tag,
      aux_sym_source_file_repeat1,
  [206] = 5,
    ACTIONS(54), 1,
      anon_sym_LT,
    ACTIONS(57), 1,
      anon_sym_LT_SLASH,
    ACTIONS(59), 1,
      sym_text,
    ACTIONS(62), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(11), 3,
      sym_tag,
      sym_interpolation,
      aux_sym_content_repeat1,
  [224] = 5,
    ACTIONS(32), 1,
      anon_sym_LT,
    ACTIONS(38), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(65), 1,
      anon_sym_LT_SLASH,
    ACTIONS(67), 1,
      sym_text,
    STATE(11), 3,
      sym_tag,
      sym_interpolation,
      aux_sym_content_repeat1,
  [242] = 4,
    ACTIONS(5), 1,
      anon_sym_LTscript_GT,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    STATE(10), 4,
      sym_script_tag,
      sym__statement,
      sym_tag,
      aux_sym_source_file_repeat1,
  [258] = 1,
    ACTIONS(71), 4,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      anon_sym_AT,
      anon_sym_POUND,
  [265] = 1,
    ACTIONS(73), 4,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      anon_sym_AT,
      anon_sym_POUND,
  [272] = 1,
    ACTIONS(75), 4,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      anon_sym_AT,
      anon_sym_POUND,
  [279] = 1,
    ACTIONS(77), 4,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      anon_sym_AT,
      anon_sym_POUND,
  [286] = 1,
    ACTIONS(79), 4,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      anon_sym_AT,
      anon_sym_POUND,
  [293] = 1,
    ACTIONS(81), 4,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      anon_sym_AT,
      anon_sym_POUND,
  [300] = 1,
    ACTIONS(83), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
      anon_sym_LBRACE_LBRACE,
  [307] = 1,
    ACTIONS(85), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
      anon_sym_LBRACE_LBRACE,
  [314] = 1,
    ACTIONS(87), 4,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      anon_sym_AT,
      anon_sym_POUND,
  [321] = 1,
    ACTIONS(89), 4,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      anon_sym_AT,
      anon_sym_POUND,
  [328] = 1,
    ACTIONS(91), 4,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      anon_sym_AT,
      anon_sym_POUND,
  [335] = 1,
    ACTIONS(93), 4,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      anon_sym_AT,
      anon_sym_POUND,
  [342] = 1,
    ACTIONS(95), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
      anon_sym_LBRACE_LBRACE,
  [349] = 1,
    ACTIONS(97), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
      anon_sym_LBRACE_LBRACE,
  [356] = 1,
    ACTIONS(99), 4,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      anon_sym_AT,
      anon_sym_POUND,
  [363] = 1,
    ACTIONS(101), 4,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      anon_sym_AT,
      anon_sym_POUND,
  [370] = 1,
    ACTIONS(103), 4,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      anon_sym_AT,
      anon_sym_POUND,
  [377] = 1,
    ACTIONS(105), 4,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      anon_sym_AT,
      anon_sym_POUND,
  [384] = 1,
    ACTIONS(107), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
      anon_sym_LBRACE_LBRACE,
  [391] = 1,
    ACTIONS(109), 4,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_text,
      anon_sym_LBRACE_LBRACE,
  [398] = 1,
    ACTIONS(111), 4,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      anon_sym_AT,
      anon_sym_POUND,
  [405] = 1,
    ACTIONS(113), 4,
      anon_sym_GT,
      aux_sym_tag_name_token1,
      anon_sym_AT,
      anon_sym_POUND,
  [412] = 3,
    ACTIONS(115), 1,
      aux_sym_handler_attribute_token2,
    ACTIONS(117), 1,
      anon_sym_DQUOTE,
    STATE(19), 1,
      sym_quoted_string,
  [422] = 2,
    ACTIONS(121), 1,
      anon_sym_LT,
    ACTIONS(119), 2,
      ts_builtin_sym_end,
      anon_sym_LTscript_GT,
  [430] = 3,
    ACTIONS(123), 1,
      aux_sym_handler_attribute_token2,
    ACTIONS(125), 1,
      anon_sym_LBRACE,
    STATE(22), 1,
      sym_quoted_expression,
  [440] = 3,
    ACTIONS(125), 1,
      anon_sym_LBRACE,
    ACTIONS(127), 1,
      aux_sym_handler_attribute_token2,
    STATE(23), 1,
      sym_quoted_expression,
  [450] = 3,
    ACTIONS(125), 1,
      anon_sym_LBRACE,
    ACTIONS(129), 1,
      aux_sym_handler_attribute_token2,
    STATE(16), 1,
      sym_quoted_expression,
  [460] = 2,
    ACTIONS(107), 1,
      anon_sym_LT,
    ACTIONS(131), 2,
      ts_builtin_sym_end,
      anon_sym_LTscript_GT,
  [468] = 3,
    ACTIONS(125), 1,
      anon_sym_LBRACE,
    ACTIONS(133), 1,
      aux_sym_handler_attribute_token2,
    STATE(18), 1,
      sym_quoted_expression,
  [478] = 2,
    ACTIONS(97), 1,
      anon_sym_LT,
    ACTIONS(135), 2,
      ts_builtin_sym_end,
      anon_sym_LTscript_GT,
  [486] = 2,
    ACTIONS(109), 1,
      anon_sym_LT,
    ACTIONS(137), 2,
      ts_builtin_sym_end,
      anon_sym_LTscript_GT,
  [494] = 2,
    ACTIONS(141), 1,
      anon_sym_LT,
    ACTIONS(139), 2,
      ts_builtin_sym_end,
      anon_sym_LTscript_GT,
  [502] = 3,
    ACTIONS(117), 1,
      anon_sym_DQUOTE,
    ACTIONS(143), 1,
      aux_sym_handler_attribute_token2,
    STATE(17), 1,
      sym_quoted_string,
  [512] = 2,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    STATE(22), 1,
      sym_quoted_expression,
  [519] = 2,
    ACTIONS(147), 1,
      aux_sym_handler_attribute_token2,
    ACTIONS(149), 1,
      sym_expression_content,
  [526] = 2,
    ACTIONS(151), 1,
      aux_sym_handler_attribute_token2,
    ACTIONS(153), 1,
      sym_expression_content,
  [533] = 2,
    ACTIONS(155), 1,
      aux_sym_handler_attribute_token1,
    ACTIONS(157), 1,
      anon_sym_EQ,
  [540] = 2,
    ACTIONS(159), 1,
      aux_sym_handler_attribute_token1,
    ACTIONS(161), 1,
      anon_sym_EQ,
  [547] = 2,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    STATE(23), 1,
      sym_quoted_expression,
  [554] = 2,
    ACTIONS(163), 1,
      aux_sym_handler_attribute_token1,
    ACTIONS(165), 1,
      anon_sym_EQ,
  [561] = 2,
    ACTIONS(167), 1,
      aux_sym_tag_name_token1,
    STATE(77), 1,
      sym_tag_name,
  [568] = 2,
    ACTIONS(169), 1,
      aux_sym_handler_attribute_token1,
    ACTIONS(171), 1,
      anon_sym_EQ,
  [575] = 2,
    ACTIONS(173), 1,
      anon_sym_DQUOTE,
    STATE(25), 1,
      sym_quoted_string,
  [582] = 2,
    ACTIONS(175), 1,
      anon_sym_EQ,
    ACTIONS(177), 1,
      aux_sym_handler_attribute_token2,
  [589] = 2,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    STATE(14), 1,
      sym_quoted_expression,
  [596] = 2,
    ACTIONS(179), 1,
      aux_sym_handler_name_token1,
    STATE(51), 1,
      sym_handler_name,
  [603] = 2,
    ACTIONS(181), 1,
      aux_sym_handler_attribute_token2,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
  [610] = 2,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    STATE(29), 1,
      sym_quoted_expression,
  [617] = 2,
    ACTIONS(185), 1,
      aux_sym_handler_attribute_token2,
    ACTIONS(187), 1,
      anon_sym_RBRACE_RBRACE,
  [624] = 2,
    ACTIONS(167), 1,
      aux_sym_tag_name_token1,
    STATE(100), 1,
      sym_tag_name,
  [631] = 2,
    ACTIONS(189), 1,
      aux_sym_handler_name_token1,
    STATE(55), 1,
      sym_directive_name,
  [638] = 2,
    ACTIONS(191), 1,
      aux_sym_handler_attribute_token2,
    ACTIONS(193), 1,
      anon_sym_RBRACE,
  [645] = 2,
    ACTIONS(195), 1,
      anon_sym_LT_SLASHscript_GT,
    ACTIONS(197), 1,
      sym_javascript_content,
  [652] = 2,
    ACTIONS(173), 1,
      anon_sym_DQUOTE,
    STATE(19), 1,
      sym_quoted_string,
  [659] = 2,
    ACTIONS(199), 1,
      anon_sym_DQUOTE,
    ACTIONS(201), 1,
      sym_string_content,
  [666] = 2,
    ACTIONS(203), 1,
      anon_sym_EQ,
    ACTIONS(205), 1,
      aux_sym_handler_attribute_token2,
  [673] = 2,
    ACTIONS(167), 1,
      aux_sym_tag_name_token1,
    STATE(88), 1,
      sym_tag_name,
  [680] = 2,
    ACTIONS(167), 1,
      aux_sym_tag_name_token1,
    STATE(89), 1,
      sym_tag_name,
  [687] = 2,
    ACTIONS(167), 1,
      aux_sym_tag_name_token1,
    STATE(90), 1,
      sym_tag_name,
  [694] = 2,
    ACTIONS(167), 1,
      aux_sym_tag_name_token1,
    STATE(2), 1,
      sym_tag_name,
  [701] = 2,
    ACTIONS(167), 1,
      aux_sym_tag_name_token1,
    STATE(91), 1,
      sym_tag_name,
  [708] = 2,
    ACTIONS(207), 1,
      aux_sym_handler_attribute_token2,
    ACTIONS(209), 1,
      anon_sym_RBRACE_RBRACE,
  [715] = 2,
    ACTIONS(167), 1,
      aux_sym_tag_name_token1,
    STATE(3), 1,
      sym_tag_name,
  [722] = 1,
    ACTIONS(211), 1,
      anon_sym_GT,
  [726] = 1,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
  [730] = 1,
    ACTIONS(215), 1,
      anon_sym_EQ,
  [734] = 1,
    ACTIONS(217), 1,
      anon_sym_GT,
  [738] = 1,
    ACTIONS(219), 1,
      anon_sym_EQ,
  [742] = 1,
    ACTIONS(221), 1,
      anon_sym_RBRACE,
  [746] = 1,
    ACTIONS(223), 1,
      ts_builtin_sym_end,
  [750] = 1,
    ACTIONS(225), 1,
      anon_sym_LT_SLASH,
  [754] = 1,
    ACTIONS(227), 1,
      sym_expression_content,
  [758] = 1,
    ACTIONS(229), 1,
      anon_sym_DQUOTE,
  [762] = 1,
    ACTIONS(231), 1,
      anon_sym_LT_SLASH,
  [766] = 1,
    ACTIONS(233), 1,
      anon_sym_GT,
  [770] = 1,
    ACTIONS(235), 1,
      anon_sym_GT,
  [774] = 1,
    ACTIONS(237), 1,
      anon_sym_GT,
  [778] = 1,
    ACTIONS(239), 1,
      anon_sym_GT,
  [782] = 1,
    ACTIONS(241), 1,
      anon_sym_RBRACE_RBRACE,
  [786] = 1,
    ACTIONS(243), 1,
      sym_expression_content,
  [790] = 1,
    ACTIONS(245), 1,
      anon_sym_RBRACE_RBRACE,
  [794] = 1,
    ACTIONS(247), 1,
      anon_sym_LT_SLASH,
  [798] = 1,
    ACTIONS(249), 1,
      anon_sym_LT_SLASHscript_GT,
  [802] = 1,
    ACTIONS(251), 1,
      anon_sym_LT_SLASH,
  [806] = 1,
    ACTIONS(253), 1,
      anon_sym_EQ,
  [810] = 1,
    ACTIONS(255), 1,
      anon_sym_GT,
  [814] = 1,
    ACTIONS(257), 1,
      anon_sym_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 28,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 81,
  [SMALL_STATE(6)] = 106,
  [SMALL_STATE(7)] = 127,
  [SMALL_STATE(8)] = 148,
  [SMALL_STATE(9)] = 169,
  [SMALL_STATE(10)] = 190,
  [SMALL_STATE(11)] = 206,
  [SMALL_STATE(12)] = 224,
  [SMALL_STATE(13)] = 242,
  [SMALL_STATE(14)] = 258,
  [SMALL_STATE(15)] = 265,
  [SMALL_STATE(16)] = 272,
  [SMALL_STATE(17)] = 279,
  [SMALL_STATE(18)] = 286,
  [SMALL_STATE(19)] = 293,
  [SMALL_STATE(20)] = 300,
  [SMALL_STATE(21)] = 307,
  [SMALL_STATE(22)] = 314,
  [SMALL_STATE(23)] = 321,
  [SMALL_STATE(24)] = 328,
  [SMALL_STATE(25)] = 335,
  [SMALL_STATE(26)] = 342,
  [SMALL_STATE(27)] = 349,
  [SMALL_STATE(28)] = 356,
  [SMALL_STATE(29)] = 363,
  [SMALL_STATE(30)] = 370,
  [SMALL_STATE(31)] = 377,
  [SMALL_STATE(32)] = 384,
  [SMALL_STATE(33)] = 391,
  [SMALL_STATE(34)] = 398,
  [SMALL_STATE(35)] = 405,
  [SMALL_STATE(36)] = 412,
  [SMALL_STATE(37)] = 422,
  [SMALL_STATE(38)] = 430,
  [SMALL_STATE(39)] = 440,
  [SMALL_STATE(40)] = 450,
  [SMALL_STATE(41)] = 460,
  [SMALL_STATE(42)] = 468,
  [SMALL_STATE(43)] = 478,
  [SMALL_STATE(44)] = 486,
  [SMALL_STATE(45)] = 494,
  [SMALL_STATE(46)] = 502,
  [SMALL_STATE(47)] = 512,
  [SMALL_STATE(48)] = 519,
  [SMALL_STATE(49)] = 526,
  [SMALL_STATE(50)] = 533,
  [SMALL_STATE(51)] = 540,
  [SMALL_STATE(52)] = 547,
  [SMALL_STATE(53)] = 554,
  [SMALL_STATE(54)] = 561,
  [SMALL_STATE(55)] = 568,
  [SMALL_STATE(56)] = 575,
  [SMALL_STATE(57)] = 582,
  [SMALL_STATE(58)] = 589,
  [SMALL_STATE(59)] = 596,
  [SMALL_STATE(60)] = 603,
  [SMALL_STATE(61)] = 610,
  [SMALL_STATE(62)] = 617,
  [SMALL_STATE(63)] = 624,
  [SMALL_STATE(64)] = 631,
  [SMALL_STATE(65)] = 638,
  [SMALL_STATE(66)] = 645,
  [SMALL_STATE(67)] = 652,
  [SMALL_STATE(68)] = 659,
  [SMALL_STATE(69)] = 666,
  [SMALL_STATE(70)] = 673,
  [SMALL_STATE(71)] = 680,
  [SMALL_STATE(72)] = 687,
  [SMALL_STATE(73)] = 694,
  [SMALL_STATE(74)] = 701,
  [SMALL_STATE(75)] = 708,
  [SMALL_STATE(76)] = 715,
  [SMALL_STATE(77)] = 722,
  [SMALL_STATE(78)] = 726,
  [SMALL_STATE(79)] = 730,
  [SMALL_STATE(80)] = 734,
  [SMALL_STATE(81)] = 738,
  [SMALL_STATE(82)] = 742,
  [SMALL_STATE(83)] = 746,
  [SMALL_STATE(84)] = 750,
  [SMALL_STATE(85)] = 754,
  [SMALL_STATE(86)] = 758,
  [SMALL_STATE(87)] = 762,
  [SMALL_STATE(88)] = 766,
  [SMALL_STATE(89)] = 770,
  [SMALL_STATE(90)] = 774,
  [SMALL_STATE(91)] = 778,
  [SMALL_STATE(92)] = 782,
  [SMALL_STATE(93)] = 786,
  [SMALL_STATE(94)] = 790,
  [SMALL_STATE(95)] = 794,
  [SMALL_STATE(96)] = 798,
  [SMALL_STATE(97)] = 802,
  [SMALL_STATE(98)] = 806,
  [SMALL_STATE(99)] = 810,
  [SMALL_STATE(100)] = 814,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attributes, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [32] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [34] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_handler_attribute, 6, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_attribute, 4, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular_attribute, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_handler_attribute, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular_attribute, 4, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 4, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_handler_attribute, 5, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_attribute, 5, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_string, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_regular_attribute, 5, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 5, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 7, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_expression, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_attribute, 6, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_expression, 5, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_expression, 4, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 6, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 8, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_name, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_tag, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_tag, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 6, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 7, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 8, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_tag, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_tag, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_handler_name, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_handler_name, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive_name, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive_name, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_name, 1, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_name, 1, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [223] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_thyn(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "thyn",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
