name: Test

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install core dependencies
        working-directory: packages/core
        run: npm install

      - name: Run core tests
        working-directory: packages/core
        run: npm test

      - name: Install vite-plugin dependencies
        working-directory: packages/vite-plugin
        run: npm install

      - name: Run vite-plugin tests
        working-directory: packages/vite-plugin
        run: npm test
